export const images = {
  logo: require('./logo.png'),
  HomeLogo: require('./home.png'),
  BellLogo: require('./bell.png'),
  AddLogo: require('./add.png'),
  SearchLogo: require('./search.png'),
  UserLogo: require('./user.png'),
  MenuLogo: require('./menus.png'),
  DotsLogo: require('./dots.png'),
  AngleLeft: require('./angle-left.png'),
  ShieldLogo: require('./shield.png'),
  StarLogo: require('./star.png'),
  CrossLogo: require('./close.png'),
  StarEmpty: require('./star_empty.png'),
  StarFill: require('./star_fill.png'),
};
